#!/usr/bin/env python3
#
# mullen - Renames files for Ms. Mullen's English Class Standard(tm)
#

import os
import configparser

print("Reading ~/.mullenrc for configuration...")

config = configparser.ConfigParser()
config.read(os.path.expanduser('~/.mullenrc'))

Settings = config['settings']
docDir = Settings['docDir']
lastName = Settings['lastName'].upper()

print("Document Dir: " + docDir)
print("Last name: " + lastName)
print("Preparing to rename files...")

for fileName in os.listdir(docDir):
    if fileName.endswith(".docx") and not fileName.startswith(lastName + "_"):
        oldName = docDir + "/" + fileName
        newName = docDir + "/"  + lastName + "_" + fileName
        print(oldName + " -> " + newName)
        os.rename(oldName, newName)
